import Image from "next/image";
import Hero from "@/components/Hero";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Maf Village</title>
        <meta name="description" content="Generated by kanjī."></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Hero
        heading="MAF VILLAGE"
        message="Adoptez les traditions sereines au coeur de Maferinya."
      />
    </div>
  );
}
